Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,6 +27,14 @@ jobs:
       run: |
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
+
+    - name: Ensure UTF-8 locale
+      run: |
+        sudo apt-get update && sudo apt-get install -y locales
+        sudo locale-gen zh_CN.UTF-8
+        export LC_ALL=zh_CN.UTF-8
+        export LANG=zh_CN.UTF-8
+        export LANGUAGE=zh_CN.UTF-8
         
     - name: Pull latest code from upstream repository
       run: |
@@ -36,34 +44,26 @@ jobs:
         # 尝试合并上游项目的最新更改
         git merge upstream/main --allow-unrelated-histories || true
 
-    # 检查合并冲突并解决，保留本地分支的  .github/workflows/main.yml 和 README.md
-    # - name: Resolve merge conflicts for main.yml and README.md
-    #   run: |
-    #     conflict_files=$(git ls-files -u | awk '{print $4}' | sort -u)
-    #     if [[ "$conflict_files" == *".github/workflows/main.yml"* ]] || [[ "$conflict_files" == *"README.md"* ]]; then
-    #       echo "Merge conflict detected in .github/workflows/main.yml or README.md, keeping current branch version"
-          
-    #       # 保留本地分支的 .github/workflows/main.yml 和 README.md 文件
-    #       git checkout --ours .github/workflows/main.yml
-    #       git checkout --ours README.md
-          
-    #       # 标记这些文件为已解决
-    #       git add .github/workflows/main.yml
-    #       git add README.md
-    #     fi
-
     # 处理所有其他未解决的冲突文件，保留本地分支的版本
+    - name: Debug conflict files
+      run: |
+        conflict_files=$(git ls-files -u | awk '{print $4}' | sort -u)
+        if [[ -n "$conflict_files" ]]; then
+          echo "Conflicting files detected:"
+          echo "$conflict_files"
+        fi
+
     - name: Resolve remaining conflicts by keeping local changes
       run: |
         remaining_conflicts=$(git ls-files -u | awk '{print $4}' | sort -u)
         if [[ -n "$remaining_conflicts" ]]; then
           echo "Resolving remaining conflicts by keeping local branch versions"
           for file in $remaining_conflicts; do
-            git checkout --ours "$file"
-            git add "$file"
+            echo "Processing $file"
+            git checkout --ours "$file" || echo "Failed to checkout: $file"
+            git add -f -- "$file"  # 使用 -f 强制添加文件
           done
         fi
-
 
     - name: Modify main.py to set about and about_video1 to empty strings
       run: |
